In [57]:
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Dataset
data = {
    "review":[
        "Excellent product",
        "Very bad quality",
        "Worth buying",
        "Waste of money",
        "Amazing performance",
        "Poor packaging",
        "Highly recommended",
        "Not satisfied"
    ],

    "label":[
        "Positive",
        "Negative",
        "Positive",
        "Negative",
        "Positive",
        "Negative",
        "Positive",
        "Negative"
    ]
}

df = pd.DataFrame(data)

# Convert Text to Numbers
vectorizer = CountVectorizer()

X = vectorizer.fit_transform(df["review"])

y = df["label"]

# Split Dataset
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.25,random_state=42
)

# KNN Model
knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train,y_train)

prediction = knn.predict(X_test)

print("Accuracy =",accuracy_score(y_test,prediction))

Accuracy = 0.0


In [58]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Spotify Dataset
data = {

    "tempo":[100,120,150,95,110,160,90,130],

    "danceability":[0.4,0.6,0.8,0.3,0.5,0.9,0.2,0.7],

    "energy":[0.5,0.7,0.9,0.4,0.6,0.95,0.3,0.8],

    "playlist":[
        "Chill",
        "Workout",
        "Workout",
        "Chill",
        "Chill",
        "Workout",
        "Chill",
        "Workout"
    ]
}

df = pd.DataFrame(data)

X = df[["tempo","danceability","energy"]]

y = df["playlist"]

X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.25,random_state=42
)

# Euclidean
euclidean = KNeighborsClassifier(
    n_neighbors=3,
    metric="euclidean"
)

euclidean.fit(X_train,y_train)

pred1 = euclidean.predict(X_test)

print("Euclidean Accuracy")

print(accuracy_score(y_test,pred1))

# Manhattan
manhattan = KNeighborsClassifier(
    n_neighbors=3,
    metric="manhattan"
)

manhattan.fit(X_train,y_train)

pred2 = manhattan.predict(X_test)

print("Manhattan Accuracy")

print(accuracy_score(y_test,pred2))

Euclidean Accuracy
0.5
Manhattan Accuracy
0.5


In [59]:
import pandas as pd

from sklearn.naive_bayes import GaussianNB

# Dataset
data = {

    "booking_time":[2,10,5,15,1,12,6,18],

    "train_popularity":[9,5,8,4,10,3,7,2],

    "travel_day":[1,5,2,6,1,7,3,5],

    "status":[
        "Confirmed",
        "Waitlisted",
        "Confirmed",
        "Waitlisted",
        "Confirmed",
        "Waitlisted",
        "Confirmed",
        "Waitlisted"
    ]
}

df = pd.DataFrame(data)

X = df.drop("status",axis=1)

y = df["status"]

model = GaussianNB()

model.fit(X,y)

prediction = model.predict([[4,8,2]])

print("Prediction =",prediction)

Prediction = ['Confirmed']


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [60]:
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import confusion_matrix

# Dataset
data={

"message":[
"Hi how are you",
"Meeting at 5",
"Congratulations you won lottery",
"Family dinner tonight",
"Project discussion",
"Click this link now",
"Birthday party tomorrow",
"Limited offer hurry"
],

"label":[
"Personal",
"Group",
"Spam",
"Personal",
"Group",
"Spam",
"Personal",
"Spam"
]

}

df=pd.DataFrame(data)

vectorizer=CountVectorizer()

X=vectorizer.fit_transform(df["message"])

y=df["label"]

X_train,X_test,y_train,y_test=train_test_split(
X,y,test_size=0.25,random_state=42
)

model=MultinomialNB()

model.fit(X_train,y_train)

prediction=model.predict(X_test)

print("Confusion Matrix")

print(confusion_matrix(y_test,prediction))

Confusion Matrix
[[0 1 0]
 [0 0 0]
 [0 1 0]]


In [61]:
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score

# Random Images (100 pixels)

X=np.random.randint(
0,
256,
(20,100)
)

# Labels

y=np.array(

["Bat"]*10+

["Football"]*10

)

X_train,X_test,y_train,y_test=train_test_split(
X,
y,
test_size=0.3,
random_state=42
)

knn=KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train,y_train)

prediction=knn.predict(X_test)

print("Accuracy")

print(accuracy_score(y_test,prediction))

Accuracy
0.5
